In [0]:
import tensorflow as tf

In [38]:
print(tf.__version__)

1.15.0


### 1) Creating and Running a Session
The first thing we should learn about Tensorflow is that is does not interpret the code line by line. It uses a uses a special funtion to run all the operations. This function is called tf.Session().                        
A session allows to execute graphs or part of graphs (seen later in this notebook)                      
It allocates resources (on one or more machines) for that and holds the actual values of intermediate results and variables.       
The execution itself is then done with the .run() method of the Session object.
When called, this method completes one set of computations in our graph in the following manner: *it starts at the requested output(s) and then works backword, computing nodes that must be executed according to the set of dependencies.*

The following is the code snippet of how Session() is used:                
sess = tf.Sesssion()                                                  
sess.run(inputs)                                                  
sess.close()       

(OR)              

with tf.Session() as sess:                                             

The second one is recommended as we dont have to close the session explicitly.

Its okay if you didn't get a clear idea about how Session() works, you will see the use to Session in every code snippet below, and thus it will be clear to you...                  
 ## Go Ahead 



## 2) Basic Maths Operations


In [0]:
# Declaring Constants in Tensowflow 

x1 = tf.constant(5)   # x1=5
x2 = tf.constant(6)   # x1=6
x3 = tf.constant(-18.0) # x3=-18

In [0]:
#result = x1*x2    This will also work
addd = tf.add(x1,x2, name="addd")                   # Adds the tensors, req. parameters:2
subb = tf.subtract(x1,x2, name="subb")              # Subtracts the tensors, req. parameters:2
multiplyy = tf.multiply(x1,x2, name="multiplyy")    # Multiply the tensors, req. parameters:2
didd = tf.divide(x1,x2, name="didd")                # Divides the tensors, req. parameters:2
addmull =  tf.add_n([x1,x2], name="addmull")        # Adds multiple Tensors of similar data types
modd = tf.math.floormod(x2,x1, name="modd")         # Performs the modulo operation on similar datatype tensors ,floor(x / y) * y + mod(x, y) = x.
abss = tf.abs(x3, name="abss")                      # Computes the absolute value
negativee = tf.negative(x3, name="negativee")       # Negates the tensor
signn = tf.sign(x3, name="signn")                   # Extracts the sign from the tensor. 1 if positive and -1 if negative
signn1 = tf.sign(x1, name="signn")   
reciprocall = tf.reciprocal(x1, name="reciprocall") # Computes the reciprocals
# This creates a tensor and will not process anything will a session is run 

In [41]:
# So, to see the result, we run it in a session
sess = tf.Session()
print(sess.run(addd))
print(sess.run(subb))
print(sess.run(multiplyy))
print(sess.run(didd))
print(sess.run(addmull))
print(sess.run(modd))
print(sess.run(abss))
print(sess.run(negativee))
print(sess.run(signn))
print(sess.run(signn1))
#print(sess.run(reciprocall))
sess.close()
#graph = tf.get_default_graph()
#print(graph.get_operations())

11
-1
30
0.8333333333333334
11
1
18.0
18.0
-1.0
1


## 3) Rounding and Comparison

In [0]:
x4 = tf.constant([-6.5, -3.5, 3.5, 6.5])
x5 = tf.constant([[1,3],[7,2]])


In [0]:
roundd = tf.round(x3, name="roundd")   # Round to the nearest integer. Req. Parameters:1
rintt = tf.rint(x3, name="rintt")      # Round to the nearest integer, round to even if there are two nearest integer. Req. Parameters:1
ceill = tf.ceil(x3, name="ceill")      # Returns the smallest integer greater than the value. Req. Parameters:1
floorr = tf.ceil(x3, name="floorr")    # Returns the greatest integer smaller than the value. Req. Parameters:1
maximumm = tf.maximum(x1,x2, name="maximumm")   # Returns the maximum tensor among the input tensors. Req. Parameters:2
minimumm = tf.minimum(x1,x2, name="minimumm")   # Returns the minimum tensor among the input tensors Req. Parameters:2
argmaxx = tf.argmax(x4, name="argmaxx")      # Returns the index of max element. Req. Parameters:1
argminn = tf.argmin(x4, name="argminn")      # Returns the index of min element. Req. Parameters:1


In [44]:
with tf.Session() as sess:
    print(sess.run(roundd))
    print(sess.run(rintt))
    print(sess.run(ceill))
    print(sess.run(floorr))
    print(sess.run(maximumm))
    print(sess.run(minimumm))
    print(sess.run(argmaxx))
    print(sess.run(argminn))

-18.0
-18.0
-18.0
-18.0
6
5
3
0


## 4) Rank and Shape of a Tensor
The rank of a tf.Tensor object is its number of dimensions. Synonyms for rank include order or degree or n-dimension. Note that rank in TensorFlow is not the same as matrix rank in mathematics.





*  Rank 0 -> Scalar (Single Value)
*  Rank 1 -> Vector (Array)
*  Rank 2 -> Matrix (Table)
*  Rank 3 -> 3-Tensor (cube of numbers)
*  Rank n -> n-Tensor (you get the idea)





In [0]:
## Rank 0 Tensors Examples 
mammal = tf.Variable("Elephant", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

## Rank 1 Tensors Examples
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

## Rank 2 Tensors Examples 
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)



In [0]:
'''
When you train a model, you use variables to hold and update parameters. Variables are in-memory buffers containing tensors. 
They must be explicitly initialized and can be saved to disk during and after training. 
You can later restore saved values to exercise or analyse the model.
'''
init_op = tf.initialize_all_variables()

In [47]:
## tf.rank() is used to get the rank of the tensor
sess = tf.Session()
sess.run(init_op)
print(sess.run(tf.rank(mammal)))
print(sess.run(mammal))
#print(sess.run(tf.rank(ignition)))
#print(sess.run(tf.rank(floating)))
#print(sess.run(tf.rank(its_complicated)))


print(sess.run(tf.rank(mystr)))
print(sess.run(mystr))
#print(sess.run(tf.rank(cool_numbers)))
#print(sess.run(tf.rank(first_primes)))
#print(sess.run(tf.rank(its_very_complicated)))

print(sess.run(tf.rank(mymat)))
print(sess.run(mymat))
#print(sess.run(tf.rank(myxor)))
#print(sess.run(tf.rank(linear_squares)))
#print(sess.run(tf.rank(squarish_squares)))
sess.close()

0
b'Elephant'
1
[b'Hello']
2
[[ 7]
 [11]]


### Shape of a tensor
The shape is the number of elements in each dimension, e.g.: 
, a vector has rank 1 and a shape of 

*   a scalar has a rank 0 and an empty shape ()
*   a vector has rank 1 and a shape of (X)
*   a matrix has rank 2 and a shape of (X, Y) and so on.

# A tensor can have maximun of 8 dimensions.![alt text](https://www.guru99.com/images/1/080418_1250_WhatisaTens2.png)

In [48]:
## tf.shape() is used to get the shape of the tensor
## RANK 0 
x6 = tf.constant(56)  
with tf.Session() as sess:
  print("Shape of x6 :", sess.run(tf.shape(x6)))
  print("Rank of x6 is :", sess.run(tf.rank(x6)))
  print(sess.run(x6))
  print("ITS A CONSTANT SO THE RANK AND SHAPE IS 0")


Shape of x6 : []
Rank of x6 is : 0
56
ITS A CONSTANT SO THE RANK AND SHAPE IS 0


In [49]:
## tf.shape() is used to get the shape of the tensor
x7 = tf.constant([18,9])  
with tf.Session() as sess:
  print("Shape of x7:", sess.run(tf.shape(x7)))
  print("Rank of x7 is :", sess.run(tf.rank(x7)))
  print(sess.run(x7))
  print("ITS A ARRAY WITH LENGTH 2, SO RANK IS 1 AND SHAPE(len of array) is 2")


Shape of x7: [2]
Rank of x7 is : 1
[18  9]
ITS A ARRAY WITH LENGTH 2, SO RANK IS 1 AND SHAPE(len of array) is 2


In [50]:
## tf.shape() is used to get the shape of the tensor
x8 = tf.constant([ [1, 1],        
                   [2, 2], 
                   [3, 3], 
                  ])  
with tf.Session() as sess:
  print("Shape of x8 (Rows and columns resp):", sess.run(tf.shape(x8)))
  print("Rank of x8 is :", sess.run(tf.rank(x8)))
  print(sess.run(x8))
  print("ITS A MATRIX IS DIMENSIONS (ROWS AND COLUMNS) 3x2, SO THE RANK IS 2 AND SHAPE IS 3X2")

Shape of x8 (Rows and columns resp): [3 2]
Rank of x8 is : 2
[[1 1]
 [2 2]
 [3 3]]
ITS A MATRIX IS DIMENSIONS (ROWS AND COLUMNS) 3x2, SO THE RANK IS 2 AND SHAPE IS 3X2


In [51]:
## tf.shape() is used to get the shape of the tensor
x9 = tf.constant([[[1, 1, 1, 1], 
                   [2, 2, 2, 2]], 
                  
                  [[3, 3, 3, 3], 
                   [4, 4, 4, 4]]]) 
with tf.Session() as sess:
  print("Shape of x9 (Rows and columns resp):", sess.run(tf.shape(x9)))
  print("Rank of x9 is :", sess.run(tf.rank(x9)))
  print("ITS A MULTIDIMENTIONAL ARRAY WITH RANK 3 AND SHAPE [2 2 3]")

Shape of x9 (Rows and columns resp): [2 2 4]
Rank of x9 is : 3
ITS A MULTIDIMENTIONAL ARRAY WITH RANK 3 AND SHAPE [2 2 3]


## 5) Creating Tensors 

In [0]:
x10 = tf.constant(25)           # Creats a constant tensor whose value cannot be change. Required parameters (value)
x11 = tf.zeros([2, 2])          # Creats a 2x2 matrix of all zeros. Required parameters (shape)
x12 = tf.ones([3, 2])           # Creats a 3x2 matrix of all onces. Required parameters (shape)
x13 = tf.fill([2, 3], 99)       # Creats a 2x3 matrix with all value = 99. Required parameters (shape, value)
x14 = tf.linspace(2.,10.,5)     # Creats a tensor containing a linear range of values. It only takes float as input and returns and 1x5 dim tensor. Required parameters (start, stop, num)
x15 = tf.range(10,50,delta=5)   # Creats a range of values with increment = value of delta, same as range in pyhton. Required parameters (start limit, delta)

In [53]:
with tf.Session() as sess:
  print("x10: ", sess.run(x10))    
  print("")
  print("x11: ",sess.run(x11))
  print("")
  print("x12: ",sess.run(x12))
  print("")
  print("x13: ",sess.run(x13))
  print("")
  print("x14: ",sess.run(x14))
  print("")
  print("x15: ",sess.run(x15))

x10:  25

x11:  [[0. 0.]
 [0. 0.]]

x12:  [[1. 1.]
 [1. 1.]
 [1. 1.]]

x13:  [[99 99 99]
 [99 99 99]]

x14:  [ 2.  4.  6.  8. 10.]

x15:  [10 15 20 25 30 35 40 45]


## 6) Creating Tensors with random values
Many Tensorflow applications required tensors that contain random values instead
of predetermined values. Tensorflow thus can also create normally distributed 
values using random_normal and truncate_normal funcations.

In [0]:
x16 = tf.random_normal([10], mean=0.0, stddev=1, name="random_normal_distribution")
# Random Normal funtion generates random values throughout the distribution with mean = 0 and standard diviation = 1
# Required Parameters (shape,mean,stddev)

x17 = tf.truncated_normal([10], mean=0.0, stddev=1, name="turncate_distribution")
# Truncate Normal funtion is same as random normal function except it removes the values which lies below and above two standard diviation. 
# Required Parameters (shape, mean, stddev)

x18 = tf.random_uniform([10], minval=0, maxval=10, name="random_uniform_distribution")
# Creates a tensor with uniformaly distributed values between the min and max value.
# Required Parameters (shape, minval, maxval)

In [55]:
with tf.Session() as sess:
  print("x16 is: ",sess.run(x16))
  print("")
  print("x17 is: ", sess.run(x16))
  print("")
  print("x18 is: ", sess.run(x18))

x16 is:  [-1.1461076  -0.02413565 -0.33261836 -1.3072872  -0.17628473 -0.44703802
  0.47290906  0.03912739 -0.2437659  -0.8332586 ]

x17 is:  [ 1.5817474   0.4296015   0.35490763  0.7554337  -0.11347314  0.68584996
  0.8362397   0.9908679   0.8154049   0.8394619 ]

x18 is:  [6.0906816 8.96202   1.6181362 4.1257915 3.9249694 6.6718807 8.613025
 9.6750555 0.5791795 4.2164803]


## 7) Transforming Tensors 

In [56]:
'''
We will use the follow tensors
x6 = tf.constant(56)                  Rank: 0, Shape: 1

x7 = tf.constant([18,9])              Rank: 1, Shape: 2

x8 = tf.constant([ [1, 1],            Rank: 2, Shape: [3,2]
                   [2, 2], 
                   [3, 3], 
                  ])  

x9 = tf.constant([[[1, 1, 1, 1],      Rank: 3, Shape: [2, 2, 3]
                   [2, 2, 2, 2]], 
                  
                  [[3, 3, 3, 3], 
                   [4, 4, 4, 4]]]) 
'''

'\nWe will use the follow tensors\nx6 = tf.constant(56)                  Rank: 0, Shape: 1\n\nx7 = tf.constant([18,9])              Rank: 1, Shape: 2\n\nx8 = tf.constant([ [1, 1],            Rank: 2, Shape: [3,2]\n                   [2, 2], \n                   [3, 3], \n                  ])  \n\nx9 = tf.constant([[[1, 1, 1, 1],      Rank: 3, Shape: [2, 2, 3]\n                   [2, 2, 2, 2]], \n                  \n                  [[3, 3, 3, 3], \n                   [4, 4, 4, 4]]]) \n'

In [57]:
with tf.Session() as sess:
  x19 = tf.cast(x6, tf.float32)           # Used to convert the data type of tensors. Req Parameter (tensor, dtype)
  print(sess.run(x19))
  print("")
  x20 = tf.reshape(x8, [1,6])             # Reshapes the tensors. It cannot remove any element, so it accepts the shape in which the product of the rows and columns is equal to the number of elements in the tensor.
  print(sess.run(x20))
  print("")
  x21 = tf.reshape(x9,[1,4,4])
  print(sess.run(x21))
  print("")
  x22 = tf.squeeze(x9)                    # Removes dimensions of size 1
  print(sess.run(x22))
  print("Shape of x22: ",sess.run(tf.shape(x22)))
  print("")
  

56.0

[[1 1 2 2 3 3]]

[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]
  [4 4 4 4]]]

[[[1 1 1 1]
  [2 2 2 2]]

 [[3 3 3 3]
  [4 4 4 4]]]
Shape of x22:  [2 2 4]



In [58]:
# Lets discuss tf.reverse()
# tf.reverse() reverses given dimensions of the tensor.
# tf.reverse() is a bit complicated, required parameters are (tensor, axis),
# The range of the axis is [-4,4). Means -4 is included but 4 is excluded. 
x23 = [[[[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                  [ 8,  9, 10, 11]],
                 [[12, 13, 14, 15],
                  [16, 17, 18, 19],
                  [20, 21, 22, 23]]]]
with tf.Session() as sess:
  print("Rank of x23 is:", sess.run(tf.rank(x23)))
  print("Shape of x23 is: ", sess.run(tf.shape(x23)))

Rank of x23 is: 4
Shape of x23 is:  [1 2 3 4]


In [59]:
with tf.Session() as sess:
  x24 = tf.reverse(x23,[0])
  print(sess.run(x24))



[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]


In [61]:
# Lets Discuss tf.slice()
# tf.slice() extracts a protion of a tensor
# Required Parameters are (tensor, begin, size) where begin is the location from where the slicing will start (location is accoring to matrix in maths) and 
# The slice size is represented as a tensor shape, where size[i] is the number of elements of the 'i'th dimension of input_ that you want to slice. 


x25 = tf.constant(([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]]))
with tf.Session() as sess:
  print("Rank of x25: ", sess.run(tf.rank(x25)))
  print("Shape of x25: ", sess.run(tf.shape(x25)))
  print("")
  print("Slice1: ", sess.run(tf.slice(x26, [1, 0, 0], [1, 1, 3])))
  print("")
  print("Slice2: ", sess.run(tf.slice(x26,[1, 0, 0], [2, 1, 3])))

Rank of x25:  3
Shape of x25:  [3 2 3]

Slice1:  [[[3 3 3]]]

Slice2:  [[[3 3 3]]

 [[5 5 5]]]


In [62]:
# Some one simple examples of slicing..
x27 = tf.constant([26,25,24,23,22,21,20])           # Simple Array
x28 = tf.constant([[2,1,3],[5,6,4],[8,9,7]])        # Simple 3x3 Matrix
with tf.Session() as sess:
  print(sess.run(tf.rank(x27)),sess.run(tf.shape(x27)))
  print(sess.run(tf.slice(x27,[3],[4])))
  print("")
  print(sess.run(tf.slice(x28,[1,1],[2,2])))

1 [7]
[23 22 21 20]

[[6 4]
 [9 7]]


In [67]:
# Lets learn about tf.stack()
# It combines a list of tensors into a tensor of greater rank
'''
Packs the list of tensors in values into a tensor with rank one higher than each tensor in values, by packing them along the axis dimension. 
Given a list of length N of tensors of shape (A, B, C);
if axis == 0 then the output tensor will have the shape (N, A, B, C). 
if axis == 1 then the output tensor will have the shape (A, N, B, C). Etc.
''' 
# Required parameters (tensors, axis=0)

x29 = tf.constant([1,2,3], name="x29")      # Rank and shape of x29,x30,x31 is 1 , [3]
x30 = tf.constant([4,5,6], name="x30")
x31 = tf.constant([7,8,9], name="x31")

with tf.Session() as sess:
  x32 = tf.stack([x29,x30,x31], axis=0)
  print(sess.run(x32))

# Thus, axis=0 will combine them row wise and axis=1 will combine them column wise.


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
# Next is obviously tf.unstack()
# It splits a tensor into a list of tensors of lesser rank.
# Required parameters (tensor, num=None,axis=0)

'''
Unpacks num tensors from value by chipping it along the axis dimension. 
If num is not specified (the default), it is inferred from value's shape. If value.shape[axis] is not known, ValueError is raised.
For example, given a tensor of shape (A, B, C, D);
If axis == 0 then the i'th tensor in output is the slice value[i, :, :, :] and each tensor in output will have shape (B, C, D). 
(Note that the dimension unpacked along is gone, unlike split).
If axis == 1 then the i'th tensor in output is the slice value[:, i, :, :] and each tensor in output will have shape (A, C, D). Etc.
'''

with tf.Session() as sess:
  x33 = tf.unstack(x32,axis=0)
  print(sess.run(x33))

[array([1, 2, 3], dtype=int32), array([4, 5, 6], dtype=int32), array([7, 8, 9], dtype=int32)]


## 8) Exponents and Logarithms

In [0]:
''' I am just up all the functions availale to get a clear idea of what it is..
I am not providing examples coz I believe you already have the idea as 
it is similar to that of provided in numpy
'''

# tf.square(x,name)                         Returns the square of the argument
# tf.squared_difference(x,y,name)           Subtracts the first argument from the second and returns the square 
# sqrt(x,name)                              Returns the square root of the argument
# rsqrt(x,name)                             Returns the reciprocal of the square root
# pow(x,y,name)                             Returns element of the first tensor raised to the power of the element of the second tensor
# exp(x,name)                               Returns the exponential function of the argument
# expm1(x,name)                             Returns the exponential function of the argument minus one, exp(x) - 1
# log(x,name)                               Returns the natural log of the argument
# log1p(x,name)                             Return log(x+1)
# erf(x,name)                               Returns the error function


## 9) Vector and Matrix Operation

In [70]:
'''
We will use these tensors
x29 = tf.constant([1,2,3])      # Rank and shape of x29,x30,x31 is 1 , [3]
x30 = tf.constant([4,5,6])
x31 = tf.constant([7,8,9])
'''
x40 = tf.constant([[1,2,3],[4,5,6],[7,8,9]], name="x40")      # Simple 3x3 Matrix
x41 = tf.constant([[9,8,7],[6,5,4],[3,2,1]], name="x41")      # Simple 3x3 Matrix

with tf.Session() as sess:
  
  x34 = tf.tensordot(x29,x30,1)     # Returns the sum of products for the elements in the given axes. Req Parameters (a,b,axes)
  print("Dot product of x29 and x30 is: ",sess.run(x34))
  print("")

  
  x35 = tf.cross(x30,x31)           # Returns the element wise cross product
  print("Cross product of x30 and x31 is: ", sess.run(x35))
  print("")

  
  x36 = tf.diag([1,2,3,4])          # Returns a matrix with given diagonal value, others set to zero. Req parameter (array of values)
  print("Matrix (x36) with given diagonal value is:", sess.run(x36))
  print("")
  
  
  x37 = tf.trace(x36)               # Return the sum of the diagonal values. Req Parameters (matrix tensor)
  print("Sum of diagonal values of x36 is: ", sess.run(x37))
  print("")
  
  
  x38 = tf.transpose(x36)           # Switches rows and columns. Req parameters (matrix tensor)
  print("Transpose of x36 is: ", sess.run(x38))
  print("")
  
  
  x39 = tf.matmul(x40,x41,transpose_a=False,transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False)          
  # Returns the product of the two input matrices. Req Parameters (a,b)
  # Can also calculate matrix multiplications with transposes and adjoints of both matrix
  print("Matrix Multiplication of x40 and x41 is: ", sess.run(x39))
  print("")
  
  
  x42 = tf.cast(x41,tf.float32)
  #print(sess.run(x42))
  
  
  x43 = tf.norm(x42,ord=1,axis=0,keep_dims=False)
  print("Norm of x40", sess.run(x43))
  # tf.norm() returns the norm of the given axis of the input tensor with the specified order. 
  # ord: Order of the norm. Supported values are 'fro', 'euclidean', 1, 2, np.inf and any positive real number yielding the corresponding p-norm.

  ''' 
  Other Function includes:
  * tf.matrix_solve(A,b,adjoint=None,name)                   Returns the tensor x, such that Ax = b, where A is a matrix and b in a vector
  * tf.qr(input,full_matrices=None,name)                     Return the eigenvectors and eigenvalues of the given matrix or matrices
  * tf.scd(tensor,full_matrices=False,compute_uv=True)       Factors the matrix into a unitary matrix
  '''

Dot product of x29 and x30 is:  32

Cross product of x30 and x31 is:  [-3  6 -3]

Matrix (x36) with given diagonal value is: [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Sum of diagonal values of x36 is:  10

Transpose of x36 is:  [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Matrix Multiplication of x40 and x41 is:  [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Norm of x40 [18. 15. 12.]


## 10) Executing Graphs in Session
When an aplication executes a Tensorflow function that creats, transforms or 
processes a tensor, the function doesn't execute its operations. Instead, 
it stores its operation in a data structure called a graph. A graph hold many
operations, and they're not execute until the application executes the graph in
a sessio. When a session executes a graph, it performs the graph's operations 
in order. 
The benefit of storing operations in a graph is that the graph can be exported 
to a file or launched on a remote system.

## Forming Graphs

* A graph contains nodes and edges similar to that or normal graph in maths.
* Nodes contains the variables or constants and edges represents the relationship between the variables/constants.
* Graphs cannot be nested and only one graph can be active at a time.
* An application can access its default graph by calling get_default_graph().
* An application can create a new graph by calling tf.graph().
* The Graph class provides many methods that access and modify the graph's 
contents.



### Accessing graph data
A graph stores its elements in a set of named collections.


The following represents all the method of Graph class that are use to access 
and update these collections.
* get_tensor_by_name(name):                       
Returns the tensor with the given name.

* get_operation_by_name(name):                               
Returns the operation with the given name

* get_operations():                             
Returns a list containing the graph's operations

* get_all_collection_keys():                                   
Returns a list of graph's collection

* get_collection(name,scope=None):                             
Returns a list of values in the given collection

* add_to_collection(name, value):                    
Adds the value to the container, can be accessed with name

* add_to_collections(name, value):                    
Adds the values to the containers, can be accessed with name



In [0]:
print(tf.get_default_graph().get_operations())
# It literally prints all the operations used across this notebook

### Lets create a new graph.

In [119]:
default_graph = tf.get_default_graph() 

newgraph = tf.Graph()                    
# Created new graph named "newgraph".

# So now we have two graphs, one default graph names "default_graph" and one is newly created graph names "newgraph". 

with newgraph.as_default():
  x44 = tf.constant([1.1,2.1,3.1], name= "x44")       
  x45 = tf.constant([1.2,2.2,3.2], name="x45")
  x46 = tf.constant([1.3,2.3,3.3], name="x46")
# So the tensors created above (x44,x45,x46) will be stored in newgraph as NODES.

x47 = tf.constant(55)
x48 = tf.constant(45)
# And the tensor which is created outsite the scope of newgraph.as_default() will be added to "default_graph" as NODES.

# We can check which tensor is added to which graph with the help of the following command.
print(x44.graph is newgraph)
print(x45.graph is newgraph)
print(x46.graph is newgraph)

print(x47.graph is newgraph)
print(x48.graph is newgraph)
print(x47.graph is default_graph) 
print(x48.graph is default_graph) 

True
True
True
False
False
True
True


In [130]:
x49 = tf.tensordot(x44,x45,1)
tf.identity(x49, name="x49")
x50 = tf.add(x47,x48)

print(x49.graph is default_graph)      # FALSE
print(x49.graph is newgraph)           # TRUE
print("So x49 is in newgraph")

print(x50.graph is default_graph)      # TRUE
print(x50.graph is newgraph)           # FALSE
print("So x50 is NOT in newgraph, its in default_graph")
# This means tensors created by performing operations with tensors under new graph will be added to that new graph. 

False
True
So x49 is in newgraph
True
False
So x50 is NOT in newgraph, its in default_graph


In [142]:
# Examples of get_tensor_by_name()

with tf.Session(graph=newgraph) as sess:
  test1 = sess.graph.get_operations()
# print(test1)
  test2 = sess.graph.get_tensor_by_name("x44:0")          # While using the name, add :0
  print(test2)
  test3 = sess.graph.get_tensor_by_name("x45:0")
  print(test3)
  print(sess.run(x49))
  test4 = sess.graph.get_tensor_by_name("x49:0")
  print(test4)
  
  

Tensor("x44:0", shape=(3,), dtype=float32)
Tensor("x45:0", shape=(3,), dtype=float32)
15.86
Tensor("x49:0", shape=(), dtype=float32)


In [147]:
# Examples of get_operation_by_name(), get_all_collection_keys()


newgraph1 = tf.Graph()
with tf.Session(graph=newgraph1) as sess:
  x51 = tf.constant(55)
  x52 = tf.constant(45)
  print(x51.graph is newgraph1)
  print(x52.graph is newgraph1)
  test5 = tf.add(x51,x52,name="test5")
  print(sess.run(test5))
  print("")
  print(sess.graph.get_operation_by_name("test5"))
  print("")


True
True
100

name: "test5"
op: "Add"
input: "Const"
input: "Const_1"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}




In [160]:
with tf.Session() as sess:
  print(sess.graph.get_all_collection_keys())
#  for op in tf.get_default_graph().get_operations():
#    print(str(op.name))
# The above code will print all the nodes present in the default graph

#with tf.Session(graph=newgraph) as sess:
#  for op in sess.graph.get_operations():
#    print(str(op.name))

# The above code will print all the nodes present in the newgraph

['trainable_variables', 'variables']


### So, we learned the following concepts about the graph in tensorflow:
* All the tensors are stored in default graph, which is called by          
graph = tf.get_default_graph()
* We can create a new graph by the following code              
 new_graph = tf.Graph()                                      
* To store the tensors in the new graph, we use the following code:             with new_graph.as_default()
* If we want to run any operations in our new graph created, like add, multiply
etc. We need to explicitly define the new graph while calling the session.      
with tf.Session(graph=new_graph) as sess:                           
Otherwise it will use the default graph. 
* Executing any graph operations like get_operations() and all will be done as 
follows.                           
sess.graph.get_operations() .. etc

## 11) Interactive Session
Rather than send an entire scripts to an interpreter, many Python developers 
prefer to write code interactively. In this mode, the interpreter displays 
feedback as each line is processed.                       
To support interactive development, Tensorflow provides the Interactive Session
class. It servers the same role as Session, but it makes itself the default 
session when it's constructed.                             
Instead of calling sess.run, you can evaluate tensors by calling their eval
method. Similarly, you can execute operations by calling the run method of the 
Operation Class

In [163]:
x53 = tf.constant(1.2)
x54 = tf.constant(3.5)
prod = tf.multiply(x53,x54)
sess = tf.InteractiveSession()            
print("Product is: ", prod.eval())

Product is:  4.2000003


/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


# 12) Variables and Placeholders 

### Variables
Unlike other Tensorflow objects that are "refilled" with data each time we 
run the session, Variables can maintain a fixed state in the graph. This is 
important because their current state might influence how they change in the 
following iteration. Like other Tensors, Variables can be used as input
for other operations in the graph.                
Using the Variables is done in two stages:                    
* First we call the tf.variable() function in order to create a Variable and 
define what value it will be initialized with.                  
* We then have to explicitly perform an initialization operation by running
the session with the tf.global_variable_initializer() method, which allocates 
the memory for the Variable and sets its inital values.

In [183]:
# Lets look at an example.

x55 = tf.random_normal((1,5),0,1)
x56 = tf.Variable(x55, name="x56")                                        # Variable is created and values are defined.
print("Before initializing the global variable: \n", format(x56))

init = tf.global_variables_initializer()

with tf.Session() as sess:
  sess.run(init)
  post_init = sess.run(x56)

print("\nAfter initializing the global variable: \n", format(post_init))


Before initializing the global variable: 
 <tf.Variable 'x56_3:0' shape=(1, 5) dtype=float32_ref>

After initializing the global variable: 
 [[ 0.3524621   1.3662233  -1.850988    0.21862166 -0.5396629 ]]


### Placeholders
So far we've used source operations to create our input data. Tensorflow,
however has designated built-in structures for feeding input values. These 
structures are calles placeholders. Placeholders can be thought of as empty 
Variables that will be filled with data later on. We use them by first 
constructing our graph and only when it is executed feeding them with the input
data.                                         
Whenever we define a placeholder, we must feed it with some input values or else an exception will be thrown. The input data is passed to the session.run()
method as a dictionary, where each key corresponds to the placeholder variable name, and the matching values are the data values of the placeholder.


In [189]:
# Lets see an example of placeholder
import numpy as np

x57 = np.random.randn(5,10)                        # A random 5x10 matrix is created using numpy
x58 = np.random.randn(10,1)                        # A random 10x1 vector is created using numpy


with tf.Graph().as_default():
  x = tf.placeholder(tf.float32,shape=(5,10))      # x is a 5x10 matrix 
  w = tf.placeholder(tf.float32,shape=(10,1))      # w is 10x1 vector 
  b = tf.fill((5,1),-1.)                           # b is constant 5x1 vector with all values -1 ie b = [-1,-1,-1,-1,-1]
  xw = tf.matmul(x,w)                              # xw is the resultant vector of the matrix multiplication of x and w, shape will be 5x1

  xwb = xw + b                                     # vector xw is added to vector b
  s = tf.reduce_max(xwb)                           # tf.reduce_max() will return the max value of the vector xwb and store it in s
  with tf.Session() as sess:
    outs = sess.run(s,feed_dict={x: x57,w: x58})     # Value of x57 is stored in placeholder w and value of x58 is stored in placeholder w

print("Output = {}".format(outs))

Output = 1.377558708190918
